apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: order-service
build:
  artifacts:
  - image: ernestoacostacuba/order-service
    buildpacks:
      builder: gcr.io/paketo-buildpacks/builder:base
      env:
        - BP_JVM_VERSION=11.*
#    jib:
#      args:
#        - -Pjib
#        - -DskipTests=true
  tagPolicy:
    gitCommit: {
                 variant: AbbrevTreeSha,
                 ignoreChanges: true
    }

  local:
    push: false

deploy:
  kubectl:
    manifests:
    - k8s/*.yml
