server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s

spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: h${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  r2dbc:
    username: ${DB_USERNAME:order_user}
    password: ${DB_PASSWORD:b3JkZXJfdXNlcgo=}
    url: r2dbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:polardb_catalog}?useSSL=false&allowPublicKeyRetrieval=true
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:polardb_catalog}?useSSL=false&allowPublicKeyRetrieval=true
    table: order_service_flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 0

polar:
  catalog-service-uri: "http://localhost:9001"
  client-time-out: 2