apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ernestoacostacuba/order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:  # Makes K8 wait 5s before sending the SIGTERM signal to the Pod
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: DB_HOST
              value: polar-mysql
            - name: DB_NAME
              value: polardb_catalog
            - name: DB_USERNAME
              value: order_user
            - name: DB_PASSWORD
              value: b3JkZXJfdXNlcgo=

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 9002