name: CI Pipeline # Name of the pipeline
on: [push]  # When the pipeline should be executed: on push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04 #The operating system on which the pipeline should run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Checks the application repository out
      - name: Set up JDK
        uses: actions/setup-java@v2 # Configures the JDK setup
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Compile and test application  # Ensures the Maven wrapper is executable
        run: |
          chmod +x mvnw
          ./mvnw test package